#!/bin/sh

echo "To trigger PiP, TAP the video and then TAP PiP button at leftmost (or rightmost)"
echo "To trigger PiP, TAP the video and then TAP PiP button at leftmost (or rightmost)"
echo "To trigger PiP, TAP the video and then TAP PiP button at leftmost (or rightmost)"
