#!/bin/bash

echo "To trigger PiP, DISMISS the app once the video started playing"
echo "To trigger PiP, DISMISS the app once the video started playing"
echo "To trigger PiP, DISMISS the app once the video started playing"
